name: Check in Public test
on:
  workflow_dispatch:
jobs:
    report:
      runs-on: ubuntu-latest
      environment: development
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITUsername: ${{ github.repository_owner }}
        GITUseremail: ${{ vars.EMAIL }}
      permissions:
        contents: write
        issues: write
        deployments: write
      steps:
        - name: Check out the repository to the runner
          uses: actions/checkout@v4
        - uses: chrnorm/deployment-action@v2
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            environment-url: http://my-app-url.com
            environment: development
        - name: Create report file
          run:  echo "Test push commit to the remote in the workflow" >> test.txt
        - name: Commit report
          run: |
            echo "GitHub user name is $GITUsername"
            echo "GitHub user email is $GITUseremail"
            echo "GitHub user Token is $GH_TOKEN"
            echo "github command is https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"
        - name: Commit Boomi CI-CD Package
          run: |
            git config --global user.name "$GITUsername"
            git config --global user.email $GITUseremail
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/kamboj2/TestRepo
            git checkout "${GITHUB_REF:11}"
            git add -A
            git commit -a -m "KAN-1" || true
            git push
            
        - name: Update deployment status
          uses: chrnorm/deployment-status@v2
          with:
            token: '${{ github.token }}'
            environment-url: http://my-app-url.com
            deployment-id: ${{ steps.deployment.outputs.deployment_id }}
            environment: development
